---
- name: Debian LXC Server auf PVE erstellen
  hosts: localhost
  gather_facts: false

  vars_prompt:

    - name: server_name
      prompt: Name des zu erstellenden Servers eingeben
      private: false