---
- name: Test
  hosts: localhost
  gather_facts: false

  tasks:

  - debug:
      msg: "{{ lookup('community.general.onepassword', 'Proxmox API' , field='Benutzername', vault='CI') }}"
  - debug:
      msg: "{{ lookup('community.general.onepassword', 'Proxmox API' , field='TokenID', vault='CI') }}"
  - debug:
      msg: "{{ lookup('community.general.onepassword', 'Proxmox API' , field='Anmeldedaten', vault='CI') }}"