---
- name: Test
  hosts: all
  gather_facts: true

  vars:
    test: test

  vars_prompt:
    - name: test
      prompt: "Test Variable"
      private: false
      default: "default_value"

  tasks:
    - name: Debug
      debug:
        msg: "Test Variable: {{ ansible_architecture }}"
