#SPDX-License-Identifier: MIT-0
---
# tasks file for backup-tools
- name: RCLONE installieren
  shell: |
    curl https://rclone.org/install.sh | bash
  args:
    creates: /usr/bin/rclone

- name: RCLONE Config Verzeichnis erstellen
  ansible.builtin.file:
    path: /root/.config/rclone
    state: directory
    mode: "0755"

- name: RCLONE-Konfiguration anlegen
  copy:
    dest: /root/.config/rclone/rclone.conf
    content: "{{ rclone_config | default('') }}"
  when: rclone_config is defined and rclone_config | length > 0
