---
# Update-Tasks für RCLONE
# Prüft ob RCLONE installiert ist und aktualisiert es bei Bedarf

# --- RCLONE Update ---
- name: Prüfe ob RCLONE installiert ist
  stat:
    path: /usr/bin/rclone
  register: rclone_binary

- name: RCLONE aktualisieren
  shell: curl https://rclone.org/install.sh | bash
  register: rclone_update_result
  changed_when: "'already installed' not in rclone_update_result.stdout"
  failed_when: rclone_update_result.rc not in [0, 3]
  when: rclone_binary.stat.exists
