#SPDX-License-Identifier: MIT-0
---
# handlers file for backup-tools
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart backrest
  ansible.builtin.systemd:
    name: backrest
    state: restarted
