---
# Debian-specific tasks for base-system
# Diese Datei enthält alle Aufgaben, die spezifisch für Debian-basierte Systeme sind

- name: System aktualisieren und bereinigen
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
    autoclean: true
    clean: true
    purge: true

- name: Benötigte Pakete installieren
  apt:
    name:
      - jq # JSON-Parser für die Kommandozeile
      - curl # Kommandozeilen-Tool für HTTP-Anfragen
      - htop # Erweiterte Prozess-Überwachung
      - gnupg2 # GNU Privacy Guard für Verschlüsselung und Signaturen
      - unattended-upgrades # Automatische Sicherheitsupdates
      - apt-listchanges # Benachrichtigung über Änderungen bei Updates
      - sudo # Privilegierte Kommandos ausführen
      - wget # Web-Downloader für die Kommandozeile
      - git # Versionskontrollsystem
      - zsh # Z-Shell (erweiterte Bash-Alternative)
      - unzip # Entpacken von ZIP-Archiven
      - net-tools # Netzwerk-Diagnosetools (ifconfig, netstat, etc.)
    state: present

- name: Lese installierte Pakete aus
  ansible.builtin.package_facts:
    manager: auto

- name: Nicht benötigte Pakete deinstallieren
  apt:
    name: >-
      {{ ['exim4-base'] + ([] if 'proxmox-ve' in ansible_facts.packages else ['postfix']) }}
    state: absent
    purge: true
    autoremove: true
  ignore_errors: true
  no_log: true

- name: Aufräumen diverser Dateien
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/motd # Message of the day (Login-Nachricht)
    - /root/.cloud-locale-test.skip # Cloud-Init Locale Test Skip-Datei
    - /root/.bashrc # Bash-Konfiguration (wird durch ZSH ersetzt)
    - /root/.profile # Shell-Profil (wird durch ZSH ersetzt)
    - /root/.wget-hsts # Wget HSTS Cache
    - /root/.lesshst # Less-History
    - /root/.zcompdump* # ZSH Completion Cache
    - /root/.cache # Allgemeiner Cache-Ordner
