---
# macOS-specific tasks for base-system
- name: Check if Homebrew is installed (Apple Silicon)
  stat:
    path: /opt/homebrew/bin/brew
  register: brew_binary_apple_silicon

- name: Set Homebrew path for Apple Silicon Macs
  set_fact:
    brew_path: "/opt/homebrew/bin/brew"
  when: brew_binary_apple_silicon.stat.exists

- name: Check if Homebrew needs to be installed
  set_fact:
    install_homebrew: true
  when: not brew_binary_apple_silicon.stat.exists

- name: Install Homebrew
  shell: >
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: install_homebrew is defined and install_homebrew

- name: Update Homebrew
  shell: "{{ brew_path }} update"
  when: brew_binary_apple_silicon.stat.exists
  register: brew_update_result
  changed_when: brew_update_result.stdout != ""

- name: Upgrade all Homebrew packages
  shell: "{{ brew_path }} upgrade"
  when: brew_binary_apple_silicon.stat.exists
  register: brew_upgrade_result
  changed_when: brew_upgrade_result.stdout != ""

- name: Upgrade all Homebrew casks
  shell: "{{ brew_path }} upgrade --cask"
  when: brew_binary_apple_silicon.stat.exists
  register: brew_cask_upgrade_result
  changed_when: brew_cask_upgrade_result.stdout != ""

- name: Cleanup Homebrew (remove old versions)
  shell: "{{ brew_path }} cleanup"
  when: brew_binary_apple_silicon.stat.exists
  register: brew_cleanup_result
  changed_when: brew_cleanup_result.stdout != ""

- name: Upgrade all installed Mac App Store apps
  community.general.mas:
    upgrade_all: true

- name: Run macOS software update (list available updates)
  shell: softwareupdate -l
  register: softwareupdate_list
  changed_when: false

- name: Run macOS software update (install all updates)
  shell: softwareupdate -i -a
  register: softwareupdate_result
  changed_when: "'No updates are available.' not in softwareupdate_result.stdout"
  failed_when: softwareupdate_result.rc != 0 and softwareupdate_result.rc != 2
