---
name: Lint

on:
  pull_request:
    branches: ["main"]
  push:
    branches-ignore: ["main"]

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: ['2.16', '2.17']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core~=${{ matrix.ansible-version }}.0
          pip install ansible-lint yamllint

      - name: Run ansible-lint
        run: |
          ansible-lint --version
          ansible-lint .

      - name: Run yamllint on YAML files
        run: |
          yamllint --version
          find . -name "*.yml" -o -name "*.yaml" | \
            xargs yamllint -d relaxed

  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: |
          yamllint --version
          yamllint -d relaxed .
